name: El Modulor
favicon: null
layout_spectrum: 0.75537
typography_spectrum: 0.37244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f4646'
    - '#20b0e3'
    - '#a2ddf0'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
